"use client";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useUser } from "@clerk/nextjs";
import {
  Award,
  BrainCircuit,
  CheckCircle2,
  Loader2,
  XCircle,
} from "lucide-react";
import { useEffect, useState } from "react";

interface Note {
  id: number;
  title: string;
  content: string;
  createdAt: string;
}

interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: string;
}

export default function QuizePage() {
  const { user, isLoaded } = useUser();
  const [notesList, setNotesList] = useState<Note[]>([]);
  const [isNotesLoading, setIsNotesLoading] = useState(true);

  //  Quiz states
  const [quizQuestions, setQuizQuestions] = useState<QuizQuestion[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedNoteTitle, setSelectedNoteTitle] = useState<string>("");

  // gameplay states
  const [userAnswers, setUserAnswers] = useState<{ [key: number]: string }>({});
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [score, setScore] = useState(0);

  //  load the user note
  useEffect(() => {
    const fetchNotes = async () => {
      if (!isLoaded || !user?.id) return;
      try {
        const res = await fetch(
          `${window.location.origin}/api/notes?userId=${user.id}`,
        );
        if (res.ok) {
          const data = await res.json();
          setNotesList(data);
        }
      } catch (error) {
        console.error("Error fetching notes:", error);
      } finally {
        setIsNotesLoading(false);
      }
    };
    fetchNotes();
  }, [isLoaded, user]);

  // generate quiz questions using ai

  const generateQuiz = async (note: Note) => {
    setIsGenerating(true);
    setQuizQuestions([]);
    setUserAnswers({});
    setIsSubmitted(false);
    setScore(0);
    setSelectedNoteTitle(note.title);

    try {
      const res = await fetch(`${window.location.origin}/api/ai/quiz`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: note.content }),
      });

      const data = await res.json();
      if (res.ok) {
        setQuizQuestions(data.quiz);
      } else {
        alert(data.error || "Quiz not yet generated");
      }
    } catch (error) {
      console.error(error);
      alert("Server Error!");
    } finally {
      setIsGenerating(false);
    }
  };

  // option selector

  const handleOptionSelect = (questionId: number, option: string) => {
    if (isSubmitted) return;
    setUserAnswers((prev) => ({ ...prev, [questionId]: option }));
  };

  // score check logic
  const checkScore = () => {
    if (Object.keys(userAnswers).length < quizQuestions.length) {
      alert("Please answer All the questions");
      return;
    }
    let finalScore = 0;
    quizQuestions.forEach((q) => {
      if (userAnswers[q.id] === q.correctAnswer) {
        finalScore += 1;
      }
    });

    setScore(finalScore);
    setIsSubmitted(true);
  };

  if (!isLoaded || isNotesLoading) {
    return (
      <div className="p-6 text-center text-slate-500 animate-pulse">
        Loading Notes for Quiz...
      </div>
    );
  }

  return (
    <div className="w-full space-y-6 p-4 max-w-5xl mx-auto">
      <div>
        <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
          <BrainCircuit className="text-purple-600 h-6 w-6" /> AI Quiz Generator
        </h2>
        <p className="text-sm text-muted-foreground mt-0.5">
          Take a quiz generated by AI from your saved notes.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left side panel: Note selection area */}
        <div className="space-y-3 lg:col-span-1">
          <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider">
            Select a Note
          </h3>
          <div className="space-y-2 max-h-[400px] overflow-y-auto pr-1">
            {notesList.map((note) => (
              <Card
                key={note.id}
                className="p-4 flex items-center justify-between shadow-sm bg-white border-slate-200"
              >
                <div className="truncate pr-2">
                  <h4 className="font-semibold text-slate-800 text-sm truncate">
                    {note.title}
                  </h4>
                </div>
                <Button
                  size="sm"
                  onClick={() => generateQuiz(note)}
                  className="bg-purple-600 hover:bg-purple-700 text-white shrink-0 text-xs"
                >
                  Start Quiz
                </Button>
              </Card>
            ))}
          </div>
        </div>

        {/* Right side panel: Quiz playing area */}
        <div className="lg:col-span-2">
          {isGenerating && (
            <div className="bg-white border rounded-2xl p-12 flex flex-col items-center justify-center space-y-3 text-slate-600 shadow-sm">
              <Loader2 className="h-8 w-8 text-purple-600 animate-spin" />
              <p className="text-sm font-medium">
                🤖 Gemini is generating the quiz paper from your note...
              </p>
            </div>
          )}

          {!isGenerating && quizQuestions.length === 0 && (
            <div className="bg-slate-50 border border-dashed rounded-2xl p-12 text-center text-slate-400">
              Click the "Start Quiz" button on any note from the left panel to
              begin the test.
            </div>
          )}

          {/* Main Quiz Interface */}
          {!isGenerating && quizQuestions.length > 0 && (
            <div className="space-y-6 bg-white border border-slate-200 rounded-2xl p-6 shadow-sm">
              <div className="border-b pb-3 flex justify-between items-center">
                <h3 className="font-bold text-lg text-slate-900">
                  Topic:{" "}
                  <span className="text-purple-700">{selectedNoteTitle}</span>
                </h3>
                <span className="text-xs bg-slate-100 px-2.5 py-1 rounded-full text-slate-600 font-semibold">
                  Total: {quizQuestions.length} MCQs
                </span>
              </div>

              {/* Mapping Questions */}
              <div className="space-y-5">
                {quizQuestions.map((q, qIdx) => (
                  <div key={q.id} className="space-y-2">
                    <h4 className="font-semibold text-slate-800 text-sm">
                      {qIdx + 1}. {q.question}
                    </h4>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                      {q.options.map((option) => {
                        const isSelected = userAnswers[q.id] === option;
                        const isCorrect = q.correctAnswer === option;

                        // Custom dynamic background styling (Before and After submit)
                        let optionStyle =
                          "border-slate-200 hover:bg-slate-50 text-slate-700";
                        if (isSelected)
                          optionStyle =
                            "border-purple-600 bg-purple-50 text-purple-900 font-medium";

                        if (isSubmitted) {
                          if (isCorrect)
                            optionStyle =
                              "border-green-500 bg-green-50 text-green-900 font-medium";
                          else if (isSelected && !isCorrect)
                            optionStyle =
                              "border-red-500 bg-red-50 text-red-900 font-medium";
                        }

                        return (
                          <button
                            key={option}
                            type="button"
                            disabled={isSubmitted}
                            onClick={() => handleOptionSelect(q.id, option)}
                            className={`w-full p-3 text-left text-xs border rounded-xl transition-all flex items-center justify-between ${optionStyle}`}
                          >
                            <span>{option}</span>
                            {isSubmitted && isCorrect && (
                              <CheckCircle2 className="h-4 w-4 text-green-600 shrink-0" />
                            )}
                            {isSubmitted && isSelected && !isCorrect && (
                              <XCircle className="h-4 w-4 text-red-600 shrink-0" />
                            )}
                          </button>
                        );
                      })}
                    </div>
                  </div>
                ))}
              </div>

              {/* Action Button and Result Sheet */}
              <div className="pt-4 border-t flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                {!isSubmitted ? (
                  <Button
                    onClick={checkScore}
                    className="w-full sm:w-auto bg-purple-700 hover:bg-purple-800 text-white font-medium"
                  >
                    Submit & Check Score
                  </Button>
                ) : (
                  <div className="w-full bg-slate-50 border p-4 rounded-xl flex items-center gap-3 animate-scale-up">
                    <div className="p-2.5 bg-yellow-100 text-yellow-700 rounded-lg">
                      <Award className="h-6 w-6" />
                    </div>
                    <div>
                      <h4 className="font-bold text-slate-900 text-sm">
                        Your Score: {score} / {quizQuestions.length}
                      </h4>
                      <p className="text-xs text-slate-500">
                        {score === quizQuestions.length
                          ? "🔥 Outstanding! All answers are correct."
                          : "👍 Good effort! Review your mistakes and try again."}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
