// "use client";

// import { Button } from "@/components/ui/button";
// import { Card } from "@/components/ui/card";
// import { useUser } from "@clerk/nextjs";
// import {
//   Award,
//   BrainCircuit,
//   CheckCircle2,
//   Loader2,
//   XCircle,
// } from "lucide-react";
// import { useEffect, useState } from "react";

// interface Note {
//   id: number;
//   title: string;
//   content: string;
//   createdAt: string;
// }

// interface QuizQuestion {
//   id: number;
//   question: string;
//   options: string[];
//   correctAnswer: string;
// }

// export default function QuizePage() {
//   const { user, isLoaded } = useUser();
//   const [notesList, setNotesList] = useState<Note[]>([]);
//   const [isNotesLoading, setIsNotesLoading] = useState(true);

//   //  Quiz states
//   const [quizQuestions, setQuizQuestions] = useState<QuizQuestion[]>([]);
//   const [isGenerating, setIsGenerating] = useState(false);
//   const [selectedNoteTitle, setSelectedNoteTitle] = useState<string>("");

//   // gameplay states
//   const [userAnswers, setUserAnswers] = useState<{ [key: number]: string }>({});
//   const [isSubmitted, setIsSubmitted] = useState(false);
//   const [score, setScore] = useState(0);

//   //  load the user note
//   useEffect(() => {
//     const fetchNotes = async () => {
//       if (!isLoaded || !user?.id) return;
//       try {
//         const res = await fetch(
//           `${window.location.origin}/api/notes?userId=${user.id}`,
//         );
//         if (res.ok) {
//           const data = await res.json();
//           setNotesList(data);
//         }
//       } catch (error) {
//         console.error("Error fetching notes:", error);
//       } finally {
//         setIsNotesLoading(false);
//       }
//     };
//     fetchNotes();
//   }, [isLoaded, user]);

//   // generate quiz questions using ai

//   const generateQuiz = async (note: Note) => {
//     setIsGenerating(true);
//     setQuizQuestions([]);
//     setUserAnswers({});
//     setIsSubmitted(false);
//     setScore(0);
//     setSelectedNoteTitle(note.title);

//     try {
//       const res = await fetch(`${window.location.origin}/api/ai/quiz`, {
//         method: "POST",
//         headers: { "Content-Type": "application/json" },
//         body: JSON.stringify({ content: note.content }),
//       });

//       const data = await res.json();
//       if (res.ok) {
//         setQuizQuestions(data.quiz);
//       } else {
//         alert(data.error || "Quiz not yet generated");
//       }
//     } catch (error) {
//       console.error(error);
//       alert("Server Error!");
//     } finally {
//       setIsGenerating(false);
//     }
//   };

//   // option selector

//   const handleOptionSelect = (questionId: number, option: string) => {
//     if (isSubmitted) return;
//     setUserAnswers((prev) => ({ ...prev, [questionId]: option }));
//   };

//   // score check logic
//   const checkScore = () => {
//     if (Object.keys(userAnswers).length < quizQuestions.length) {
//       alert("Please answer All the questions");
//       return;
//     }
//     let finalScore = 0;
//     quizQuestions.forEach((q) => {
//       if (userAnswers[q.id] === q.correctAnswer) {
//         finalScore += 1;
//       }
//     });

//     setScore(finalScore);
//     setIsSubmitted(true);
//   };

//   if (!isLoaded || isNotesLoading) {
//     return (
//       <div className="p-6 text-center text-slate-500 animate-pulse">
//         Loading Notes for Quiz...
//       </div>
//     );
//   }

//   return (
//     <div className="w-full space-y-6 p-4 max-w-5xl mx-auto">
//       <div>
//         <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
//           <BrainCircuit className="text-purple-600 h-6 w-6" /> AI Quiz Generator
//         </h2>
//         <p className="text-sm text-muted-foreground mt-0.5">
//           Take a quiz generated by AI from your saved notes.
//         </p>
//       </div>

//       <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
//         {/* Left side panel: Note selection area */}
//         <div className="space-y-3 lg:col-span-1">
//           <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider">
//             Select a Note
//           </h3>
//           <div className="space-y-2 max-h-[400px] overflow-y-auto pr-1">
//             {notesList.map((note) => (
//               <Card
//                 key={note.id}
//                 className="p-4 flex items-center justify-between shadow-sm bg-white border-slate-200"
//               >
//                 <div className="truncate pr-2">
//                   <h4 className="font-semibold text-slate-800 text-sm truncate">
//                     {note.title}
//                   </h4>
//                 </div>
//                 <Button
//                   size="sm"
//                   onClick={() => generateQuiz(note)}
//                   className="bg-purple-600 hover:bg-purple-700 text-white shrink-0 text-xs"
//                 >
//                   Start Quiz
//                 </Button>
//               </Card>
//             ))}
//           </div>
//         </div>

//         {/* Right side panel: Quiz playing area */}
//         <div className="lg:col-span-2">
//           {isGenerating && (
//             <div className="bg-white border rounded-2xl p-12 flex flex-col items-center justify-center space-y-3 text-slate-600 shadow-sm">
//               <Loader2 className="h-8 w-8 text-purple-600 animate-spin" />
//               <p className="text-sm font-medium">
//                 🤖 Gemini is generating the quiz paper from your note...
//               </p>
//             </div>
//           )}

//           {!isGenerating && quizQuestions.length === 0 && (
//             <div className="bg-slate-50 border border-dashed rounded-2xl p-12 text-center text-slate-400">
//               Click the "Start Quiz" button on any note from the left panel to
//               begin the test.
//             </div>
//           )}

//           {/* Main Quiz Interface */}
//           {!isGenerating && quizQuestions.length > 0 && (
//             <div className="space-y-6 bg-white border border-slate-200 rounded-2xl p-6 shadow-sm">
//               <div className="border-b pb-3 flex justify-between items-center">
//                 <h3 className="font-bold text-lg text-slate-900">
//                   Topic:{" "}
//                   <span className="text-purple-700">{selectedNoteTitle}</span>
//                 </h3>
//                 <span className="text-xs bg-slate-100 px-2.5 py-1 rounded-full text-slate-600 font-semibold">
//                   Total: {quizQuestions.length} MCQs
//                 </span>
//               </div>

//               {/* Mapping Questions */}
//               <div className="space-y-5">
//                 {quizQuestions.map((q, qIdx) => (
//                   <div key={q.id} className="space-y-2">
//                     <h4 className="font-semibold text-slate-800 text-sm">
//                       {qIdx + 1}. {q.question}
//                     </h4>
//                     <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
//                       {q.options.map((option) => {
//                         const isSelected = userAnswers[q.id] === option;
//                         const isCorrect = q.correctAnswer === option;

//                         // Custom dynamic background styling (Before and After submit)
//                         let optionStyle =
//                           "border-slate-200 hover:bg-slate-50 text-slate-700";
//                         if (isSelected)
//                           optionStyle =
//                             "border-purple-600 bg-purple-50 text-purple-900 font-medium";

//                         if (isSubmitted) {
//                           if (isCorrect)
//                             optionStyle =
//                               "border-green-500 bg-green-50 text-green-900 font-medium";
//                           else if (isSelected && !isCorrect)
//                             optionStyle =
//                               "border-red-500 bg-red-50 text-red-900 font-medium";
//                         }

//                         return (
//                           <button
//                             key={option}
//                             type="button"
//                             disabled={isSubmitted}
//                             onClick={() => handleOptionSelect(q.id, option)}
//                             className={`w-full p-3 text-left text-xs border rounded-xl transition-all flex items-center justify-between ${optionStyle}`}
//                           >
//                             <span>{option}</span>
//                             {isSubmitted && isCorrect && (
//                               <CheckCircle2 className="h-4 w-4 text-green-600 shrink-0" />
//                             )}
//                             {isSubmitted && isSelected && !isCorrect && (
//                               <XCircle className="h-4 w-4 text-red-600 shrink-0" />
//                             )}
//                           </button>
//                         );
//                       })}
//                     </div>
//                   </div>
//                 ))}
//               </div>

//               {/* Action Button and Result Sheet */}
//               <div className="pt-4 border-t flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
//                 {!isSubmitted ? (
//                   <Button
//                     onClick={checkScore}
//                     className="w-full sm:w-auto bg-purple-700 hover:bg-purple-800 text-white font-medium"
//                   >
//                     Submit & Check Score
//                   </Button>
//                 ) : (
//                   <div className="w-full bg-slate-50 border p-4 rounded-xl flex items-center gap-3 animate-scale-up">
//                     <div className="p-2.5 bg-yellow-100 text-yellow-700 rounded-lg">
//                       <Award className="h-6 w-6" />
//                     </div>
//                     <div>
//                       <h4 className="font-bold text-slate-900 text-sm">
//                         Your Score: {score} / {quizQuestions.length}
//                       </h4>
//                       <p className="text-xs text-slate-500">
//                         {score === quizQuestions.length
//                           ? "🔥 Outstanding! All answers are correct."
//                           : "👍 Good effort! Review your mistakes and try again."}
//                       </p>
//                     </div>
//                   </div>
//                 )}
//               </div>
//             </div>
//           )}
//         </div>
//       </div>
//     </div>
//   );
// }

"use client";

import { useUser } from "@clerk/nextjs";
import {
  Award,
  BookOpen,
  ChevronRight,
  CheckCircle2,
  Flame,
  Loader2,
  Play,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Upload,
  Users,
  XCircle,
  Zap,
} from "lucide-react";
import { useEffect, useState } from "react";

// ─── Types ───────────────────────────────────────────────────────────────────
interface Note {
  id: number;
  title: string;
  content: string;
  createdAt: string;
  tags?: { label: string; color: string }[];
}

interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: string;
}

// ─── Tag colour helper (auto-assigns colours by index) ───────────────────────
const TAG_PALETTES = [
  "bg-teal-100 text-teal-700",
  "bg-purple-100 text-purple-700",
  "bg-blue-100 text-blue-700",
  "bg-yellow-100 text-yellow-700",
  "bg-green-100 text-green-700",
  "bg-orange-100 text-orange-700",
  "bg-indigo-100 text-indigo-700",
  "bg-pink-100 text-pink-700",
];

const recommended = [
  {
    id: 1,
    icon: <Zap className="h-4 w-4 text-green-600" />,
    bg: "bg-green-100",
    title: "Advanced Algorithms",
    students: "2.4k students enrolled",
  },
  {
    id: 2,
    icon: <BookOpen className="h-4 w-4 text-purple-600" />,
    bg: "bg-purple-100",
    title: "System Design Basics",
    students: "1.6k students enrolled",
  },
];

// ─── Main Component ───────────────────────────────────────────────────────────
export default function AIQuizPage() {
  const { user, isLoaded } = useUser();

  // notes list
  const [notesList, setNotesList] = useState<Note[]>([]);
  const [isNotesLoading, setIsNotesLoading] = useState(true);

  // quiz states
  const [quizQuestions, setQuizQuestions] = useState<QuizQuestion[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedNote, setSelectedNote] = useState<Note | null>(null);

  // gameplay states
  const [userAnswers, setUserAnswers] = useState<{ [key: number]: string }>({});
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [score, setScore] = useState(0);

  // UI state
  const [hoveredCard, setHoveredCard] = useState<number | null>(null);
  const [activeView, setActiveView] = useState<"select" | "quiz">("select");

  // ── Fetch notes ─────────────────────────────────────────────────────────────
  useEffect(() => {
    const fetchNotes = async () => {
      if (!isLoaded || !user?.id) return;
      try {
        const res = await fetch(
          `${window.location.origin}/api/notes?userId=${user.id}`,
        );
        if (res.ok) {
          const data = await res.json();
          setNotesList(data);
        }
      } catch (error) {
        console.error("Error fetching notes:", error);
      } finally {
        setIsNotesLoading(false);
      }
    };
    fetchNotes();
  }, [isLoaded, user]);

  // ── Generate quiz ────────────────────────────────────────────────────────────
  const generateQuiz = async (note: Note) => {
    setIsGenerating(true);
    setQuizQuestions([]);
    setUserAnswers({});
    setIsSubmitted(false);
    setScore(0);
    setSelectedNote(note);
    setActiveView("quiz");

    try {
      const res = await fetch(`${window.location.origin}/api/ai/quiz`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: note.content }),
      });
      const data = await res.json();
      if (res.ok) {
        setQuizQuestions(data.quiz);
      } else {
        alert(data.error || "Quiz not yet generated");
        setActiveView("select");
      }
    } catch (error) {
      console.error(error);
      alert("Server Error!");
      setActiveView("select");
    } finally {
      setIsGenerating(false);
    }
  };

  // ── Option select ────────────────────────────────────────────────────────────
  const handleOptionSelect = (questionId: number, option: string) => {
    if (isSubmitted) return;
    setUserAnswers((prev) => ({ ...prev, [questionId]: option }));
  };

  // ── Submit & score ───────────────────────────────────────────────────────────
  const checkScore = () => {
    if (Object.keys(userAnswers).length < quizQuestions.length) {
      alert("Please answer all the questions first.");
      return;
    }
    let finalScore = 0;
    quizQuestions.forEach((q) => {
      if (userAnswers[q.id] === q.correctAnswer) finalScore += 1;
    });
    setScore(finalScore);
    setIsSubmitted(true);
  };

  // ── Retry ────────────────────────────────────────────────────────────────────
  const handleRetry = () => {
    setUserAnswers({});
    setIsSubmitted(false);
    setScore(0);
  };

  // ── Back to select ────────────────────────────────────────────────────────────
  const handleBack = () => {
    setActiveView("select");
    setQuizQuestions([]);
    setSelectedNote(null);
    setUserAnswers({});
    setIsSubmitted(false);
  };

  // ── Loading skeleton ──────────────────────────────────────────────────────────
  if (!isLoaded || isNotesLoading) {
    return (
      <div className="min-h-screen bg-slate-100 p-6 flex items-center justify-center">
        <div className="flex flex-col items-center gap-3 text-slate-500">
          <Loader2 className="h-8 w-8 animate-spin text-purple-600" />
          <p className="text-sm font-medium animate-pulse">
            Loading your notes…
          </p>
        </div>
      </div>
    );
  }

  // ════════════════════════════════════════════════════════════════════════════
  return (
    <div className="min-h-screen bg-slate-100 p-6 font-sans">
      <div className="max-w-6xl mx-auto space-y-6">
        {/* ── Hero Card ─────────────────────────────────────────────────────── */}
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-slate-200">
          <h1 className="text-3xl font-extrabold text-slate-900 mb-2 tracking-tight">
            AI Quiz Generator
          </h1>
          <p className="text-slate-500 mb-6 text-sm max-w-md">
            Ready to Learn? Transform your notes into interactive quizzes in
            seconds with our visionary AI engine.
          </p>
          <div className="flex gap-3 flex-wrap">
            <button className="flex items-center gap-2 bg-cyan-400 hover:bg-cyan-500 text-slate-900 font-semibold px-5 py-2.5 rounded-lg text-sm transition-colors shadow-sm">
              <Sparkles className="h-4 w-4" />
              Generate from URL
            </button>
            <button className="flex items-center gap-2 bg-white hover:bg-slate-50 text-slate-700 font-semibold px-5 py-2.5 rounded-lg text-sm border border-slate-200 transition-colors shadow-sm">
              <Upload className="h-4 w-4" />
              Upload Document
            </button>
          </div>
        </div>

        {/* ── Main Grid ─────────────────────────────────────────────────────── */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* ── Left / Center column ──────────────────────────────────────── */}
          <div className="lg:col-span-2 space-y-4">
            {/* ── NOTE SELECTION VIEW ─────────────────────────────────────── */}
            {activeView === "select" && (
              <>
                <div className="flex items-center justify-between">
                  <h2 className="text-xl font-bold text-slate-900">
                    Select a Note
                  </h2>
                  <button className="flex items-center gap-1 text-sm text-purple-600 hover:text-purple-800 font-medium transition-colors">
                    View All Library
                    <ChevronRight className="h-4 w-4" />
                  </button>
                </div>

                {notesList.length === 0 ? (
                  <div className="bg-white border border-dashed border-slate-300 rounded-2xl p-12 text-center text-slate-400 text-sm">
                    No notes found. Create a note first to generate a quiz.
                  </div>
                ) : (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {notesList.map((note, idx) => {
                      // build 1-2 tag chips from note title words as fallback
                      const chips = note.tags ?? [
                        {
                          label: note.title.split(" ")[0] ?? "Note",
                          color: TAG_PALETTES[idx % TAG_PALETTES.length],
                        },
                      ];

                      const metaDate = new Date(note.createdAt);
                      const diffDays = Math.floor(
                        (Date.now() - metaDate.getTime()) / 86_400_000,
                      );
                      const metaStr =
                        diffDays === 0
                          ? "Created today"
                          : diffDays === 1
                            ? "Created yesterday"
                            : `Created ${diffDays} days ago`;

                      return (
                        <div
                          key={note.id}
                          className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm hover:shadow-md transition-shadow"
                          onMouseEnter={() => setHoveredCard(note.id)}
                          onMouseLeave={() => setHoveredCard(null)}
                        >
                          <div className="flex gap-2 flex-wrap mb-3">
                            {chips.map((tag) => (
                              <span
                                key={tag.label}
                                className={`text-xs font-semibold px-2.5 py-0.5 rounded-full ${tag.color}`}
                              >
                                {tag.label}
                              </span>
                            ))}
                          </div>
                          <h3 className="font-bold text-slate-900 text-base mb-1 leading-snug line-clamp-2">
                            {note.title}
                          </h3>
                          <p className="text-xs text-slate-400 mb-4">
                            {metaStr}
                          </p>
                          <button
                            onClick={() => generateQuiz(note)}
                            className={`w-full flex items-center justify-center gap-2 py-2.5 rounded-xl text-sm font-semibold transition-colors ${
                              hoveredCard === note.id
                                ? "bg-purple-700 text-white"
                                : "bg-purple-100 text-purple-800"
                            }`}
                          >
                            <Play className="h-4 w-4 fill-current" />
                            Start Quiz
                          </button>
                        </div>
                      );
                    })}
                  </div>
                )}
              </>
            )}

            {/* ── QUIZ VIEW ───────────────────────────────────────────────── */}
            {activeView === "quiz" && (
              <div className="space-y-4">
                {/* Back button */}
                <button
                  onClick={handleBack}
                  className="flex items-center gap-1.5 text-sm text-slate-500 hover:text-purple-700 font-medium transition-colors"
                >
                  ← Back to notes
                </button>

                {/* Generating loader */}
                {isGenerating && (
                  <div className="bg-white border rounded-2xl p-12 flex flex-col items-center justify-center gap-3 text-slate-600 shadow-sm">
                    <Loader2 className="h-8 w-8 text-purple-600 animate-spin" />
                    <p className="text-sm font-medium">
                      🤖 AI is generating your quiz from the note…
                    </p>
                  </div>
                )}

                {/* Quiz interface */}
                {!isGenerating && quizQuestions.length > 0 && (
                  <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-6">
                    {/* Header */}
                    <div className="border-b pb-3 flex justify-between items-center flex-wrap gap-2">
                      <h3 className="font-bold text-lg text-slate-900">
                        Topic:{" "}
                        <span className="text-purple-700">
                          {selectedNote?.title}
                        </span>
                      </h3>
                      <span className="text-xs bg-slate-100 px-2.5 py-1 rounded-full text-slate-600 font-semibold">
                        {quizQuestions.length} MCQs
                      </span>
                    </div>

                    {/* Questions */}
                    <div className="space-y-6">
                      {quizQuestions.map((q, qIdx) => (
                        <div key={q.id} className="space-y-2.5">
                          <h4 className="font-semibold text-slate-800 text-sm">
                            {qIdx + 1}. {q.question}
                          </h4>
                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                            {q.options.map((option) => {
                              const isSelected = userAnswers[q.id] === option;
                              const isCorrect = q.correctAnswer === option;

                              let style =
                                "border-slate-200 hover:bg-slate-50 text-slate-700";
                              if (isSelected && !isSubmitted)
                                style =
                                  "border-purple-600 bg-purple-50 text-purple-900 font-medium";
                              if (isSubmitted) {
                                if (isCorrect)
                                  style =
                                    "border-green-500 bg-green-50 text-green-900 font-medium";
                                else if (isSelected)
                                  style =
                                    "border-red-500 bg-red-50 text-red-900 font-medium";
                              }

                              return (
                                <button
                                  key={option}
                                  type="button"
                                  disabled={isSubmitted}
                                  onClick={() =>
                                    handleOptionSelect(q.id, option)
                                  }
                                  className={`w-full p-3 text-left text-xs border rounded-xl transition-all flex items-center justify-between ${style}`}
                                >
                                  <span>{option}</span>
                                  {isSubmitted && isCorrect && (
                                    <CheckCircle2 className="h-4 w-4 text-green-600 shrink-0" />
                                  )}
                                  {isSubmitted && isSelected && !isCorrect && (
                                    <XCircle className="h-4 w-4 text-red-500 shrink-0" />
                                  )}
                                </button>
                              );
                            })}
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Footer: submit / result */}
                    <div className="pt-4 border-t">
                      {!isSubmitted ? (
                        <button
                          onClick={checkScore}
                          className="w-full sm:w-auto bg-purple-700 hover:bg-purple-800 text-white font-semibold px-6 py-2.5 rounded-xl text-sm transition-colors"
                        >
                          Submit & Check Score
                        </button>
                      ) : (
                        <div className="flex flex-col sm:flex-row sm:items-center gap-4">
                          {/* Score card */}
                          <div className="flex-1 bg-slate-50 border p-4 rounded-xl flex items-center gap-3">
                            <div className="p-2.5 bg-yellow-100 text-yellow-700 rounded-lg shrink-0">
                              <Award className="h-6 w-6" />
                            </div>
                            <div>
                              <h4 className="font-bold text-slate-900 text-sm">
                                Your Score: {score} / {quizQuestions.length}
                              </h4>
                              <p className="text-xs text-slate-500">
                                {score === quizQuestions.length
                                  ? "🔥 Outstanding! All answers correct."
                                  : "👍 Good effort! Review mistakes and try again."}
                              </p>
                            </div>
                          </div>
                          {/* Retry button */}
                          <button
                            onClick={handleRetry}
                            className="bg-purple-100 hover:bg-purple-200 text-purple-800 font-semibold px-5 py-2.5 rounded-xl text-sm transition-colors shrink-0"
                          >
                            Try Again
                          </button>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* ── Right Sidebar ─────────────────────────────────────────────── */}
          <div className="space-y-4">
            {/* Progress card */}
            <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-bold text-slate-900">Your Progress</h3>
                <TrendingUp className="h-5 w-5 text-green-500" />
              </div>

              <div className="bg-slate-50 rounded-xl p-4 mb-4 flex items-center gap-3">
                <div className="p-2 bg-purple-600 rounded-xl">
                  <Flame className="h-5 w-5 text-white" />
                </div>
                <div>
                  <p className="text-xs text-slate-500 font-medium">
                    Current Streak
                  </p>
                  <p className="text-2xl font-extrabold text-slate-900 leading-tight">
                    5 Days!
                  </p>
                </div>
              </div>

              <div className="mb-4">
                <div className="flex justify-between text-xs font-medium text-slate-600 mb-1.5">
                  <span className="flex items-center gap-1">
                    <Target className="h-3.5 w-3.5 text-slate-400" />
                    Daily Goal
                  </span>
                  <span>3 / 5 Quizzes</span>
                </div>
                <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-purple-600 rounded-full"
                    style={{ width: "60%" }}
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="bg-slate-50 rounded-xl p-3 text-center">
                  <div className="flex items-center justify-center gap-1 mb-0.5">
                    <Star className="h-3.5 w-3.5 text-yellow-500" />
                    <p className="text-xs text-slate-500 font-medium">
                      Total XP
                    </p>
                  </div>
                  <p className="text-xl font-extrabold text-slate-900">
                    12,450
                  </p>
                </div>
                <div className="bg-slate-50 rounded-xl p-3 text-center">
                  <div className="flex items-center justify-center gap-1 mb-0.5">
                    <TrendingUp className="h-3.5 w-3.5 text-green-500" />
                    <p className="text-xs text-slate-500 font-medium">
                      Avg Score
                    </p>
                  </div>
                  <p className="text-xl font-extrabold text-slate-900">92%</p>
                </div>
              </div>
            </div>

            {/* Recommended */}
            <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm">
              <h3 className="font-bold text-slate-900 mb-3">
                Recommended for You
              </h3>
              <div className="space-y-3">
                {recommended.map((item) => (
                  <div
                    key={item.id}
                    className="flex items-center gap-3 cursor-pointer group"
                  >
                    <div className={`p-2.5 rounded-xl ${item.bg} shrink-0`}>
                      {item.icon}
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-slate-800 group-hover:text-purple-700 transition-colors">
                        {item.title}
                      </p>
                      <p className="text-xs text-slate-400">{item.students}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Study Groups banner */}
            <div className="relative rounded-2xl overflow-hidden h-32 shadow-sm">
              <div className="absolute inset-0 bg-gradient-to-br from-slate-800 to-slate-900" />
              <div className="absolute inset-0 opacity-20 bg-[radial-gradient(ellipse_at_top_right,_#7c3aed,_transparent)]" />
              <div className="relative p-5 h-full flex flex-col justify-end">
                <div className="flex items-center gap-1.5 mb-1">
                  <Users className="h-4 w-4 text-purple-300" />
                  <h4 className="font-bold text-white text-sm">Study Groups</h4>
                </div>
                <p className="text-xs text-slate-300">
                  Collaborate with peers worldwide.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
